# 支持的iOS系统的最低版本
platform :ios, '12.0'

# 指定开源库的下载源（组件化开发时会用到）
#source 'https://github.com/CocoaPods/Specs.git'
#source 'https://github.com/Artsy/Specs.git'
source 'https://mirrors.tuna.tsinghua.edu.cn/git/CocoaPods/Specs.git'

# ignore all warnings from all pods
inhibit_all_warnings!

target 'mo-vol-ios' do
   # 使用framework（包含swift库就必须使用此设置，纯OC库可以不设置）
   use_frameworks!

   # Pods for mo-vol-ios-templete
   pod 'AFNetworking'               # 网络基础库
   pod 'SDWebImage'                 # 图片处理
   pod 'dsBridge'                   # IOS与js交互
   pod 'HEPhotoPicker'              # 调取相册
   # pod 'WLVideo'                    # 仿微信拍照视频插件
   
   pod 'Kingfisher'
   pod 'Alamofire'
   pod 'SnapKit'
   pod 'SwiftyJSON'
   pod 'HandyJSON', '5.0.0-beta'
   pod 'Moya'
   pod 'BayMaxProtector'
     
   pod 'gsafetyCocopodsTest', '0.0.3'
   #layout
   pod 'DeviceKit'

  target 'mo-vol-iosTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'mo-vol-iosUITests' do
    # Pods for testing
  end

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
   target.build_configurations.each do |config|
    if config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'].to_f < 8.0
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '9.0'
     end
   end
  end
end
